version: 0.0.{build}

platform:
  - x64
  ################
  extraMetadata:
  main: main.js
extraResources:
  - from: static
    to: static
productName: Suzy
appId: com.electron.kurier
asar: true
compression: maximum 

##################
cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@next # force install next version to test electron-builder
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run release

test: off
